export { default as Header } from './Header'
export { default as WhatsApp } from './WhatsApp'
export { default as SejaFranqueado} from './Franqueado'
export { default as Contato} from './Contato'
export { default as FranchiseCard} from './FranchiseCard'