export const franchisees = {
  ac: [
    {
      name: 'Acre',
      address: 'Aeropostale, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Aeropostale 2',
      address: 'Aeropostale, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Xablua dsakhdkas',
      address: 'dasdas, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Acre',
      address: 'Aeropostale, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Aeropostale 2',
      address: 'Aeropostale, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Xablua dsakhdkas',
      address: 'dasdas, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Acre',
      address: 'Aeropostale, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Aeropostale 2',
      address: 'Aeropostale, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Xablua dsakhdkas',
      address: 'dasdas, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Acre',
      address: 'Aeropostale, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Aeropostale 2',
      address: 'Aeropostale, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Xablua dsakhdkas',
      address: 'dasdas, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
  ],
  al: [
    {
      name: 'Alagoas 1',
      address: 'Aeropostale, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Alagoas 2',
      address: 'Aeropostale, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
    {
      name: 'Alagoas dsakhdkas dadsa',
      address: 'dasdas, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'saeas@dasdas.com',
    },
  ],
  am: [],
  ap: [],
  ba: [],
  ce: [],
  es: [],
  go: [],
  ma: [],
  mg: [],
  ms: [],
  mt: [],
  pa: [],
  pb: [],
  pe: [],
  pi: [],
  pr: [],
  rj: [],
  rn: [],
  ro: [],
  rr: [],
  rs: [],
  sc: [],
  se: [],
  sp: [
    {
      name: 'São Paulo 1',
      address: 'Aeropostale, 75001 Paris',
      city: 'Paris',
      phone: '11 9673464234',
      email: 'xablau@daslkjdas.com'
    }
  ],
  to: [],
}