export const franchisees = {
  ac: [],
  al: [],
  am: [],
  ap: [],
  ba: [],
  ce: [],
  es: [],
  go: [],
  ma: [],
  mg: [],
  ms: [
    {
      representantes: 'REPRESENTANTES',
      estado: 'MATO GROSSO DO SUL | MS',
      nome: 'Ponto TV Dourados',
      local: 'Dourados',
      franqueado: 'Marcelo Ferreira',
      telefone: '(67) 99629-7069',
      instagram: '@pontotvgrandourados'
    },
  ],
  mt: [],
  pa: [],
  pb: [],
  pe: [],
  pi: [],
  pr: [
    {
      representantes: 'REPRESENTANTES',
      estado: 'PARANÁ | PR',
      nome: 'Ponto TV Curitiba',
      local: 'Curitiba e Região Metropolitana, Campo Largo, Campo Magro, Arapongas, Foz do Iguaçu, Londrina, Rolândia e São José dos Pinhais',
      franqueado: 'Juliano Pimentel',
      telefone: '(41) 99501-8102',
      facebook: '@pontotv',
      instagram: '@pontotvgrandourados'
    },
    {
      local: 'Curitiba e Região Metropolitana, Campo Largo, Campo Magro, Arapongas, Foz do Iguaçu, Londrina, Rolândia e São José dos Pinhais',
      franqueado: 'Juliano Pimentel',
      telefone: '(41) 99501-8102',
      facebook: '@pontotv',
      instagram: '@pontotvgrandourados'
    },
  ],
  rj: [],
  rn: [],
  ro: [],
  rr: [],
  rs: [],
  sc: [],
  se: [],
  sp: [],
  to: [],
}